server:
    port: ${port:8080}
    error.whitelabel.enabled: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: swiftleap
        url: jdbc:mysql://swiftleap-mysql/swiftleap
        username: swiftleap
ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 5000

