server:
    port: 8082
    error.whitelabel.enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: swiftleap
        url: jdbc:mysql://swiftleap-mysql/swiftleap
        username: swiftleap
    social:
        facebook:
            clientId: 1307552222602859
            clientSecret: 004e35ef68894981197d2297e7639870
        google:
            clientId: xx
            clientSecret: xx
#logging:
#    level:
#        org:
#            hibernate: ERROR
#            springframework:
#                web: INFO
#        root: INFO
#flyway:
#    baselineOnMigrate: true


